[package]
name = "matching_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
lazy_static = "1.5.0"
prometheus = "0.13.4"
uuid = { version = "1.15.1", features = ["serde", "v4", "fast-rng"] }
