{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "buy_order_price_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Asks",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sell_order_price_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Bids",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "buy_order_price_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Orders per Second over last 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(order_counter[5m])\n", "legendFormat": "Num Orders Placed" },
    {
     "expr": "rate(orders_filled_counter[5m])",
     "legendFormat": "Num Orders Filled"
    }
   ]
  },
  {
   "title": "Number of Resting Orders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_counter - orders_filled_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Matching Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Matching Duration (over time)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(matching_duration_bucket[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Matching Duration Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum by(le) (rate(matching_duration_bucket[$__rate_interval])))",
       "legendFormat": "P25"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le) (rate(matching_duration_bucket[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(matching_duration_bucket[$__rate_interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(matching_duration_bucket[$__rate_interval])))",
       "legendFormat": "P95"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rate(trade_counter[5m])\n", "legendFormat": "Trades per second" },
      { "expr": "rate(order_counter[5m])\n", "legendFormat": "Orders per second" }
     ]
    },
    {
     "title": "Trades per Second over last 5 min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "rate(trade_counter[5m])\n", "legendFormat": "Num Trades" }
     ]
    }
   ]
  }
 ]
}